### ISSUE TITLE
ERROR: Address not acknowledged.

### ISSUE THREAD

**Issue by sengiv** [cbalint13/avr-aosp#1]
Hi,
when trying to write to AVR JTAG ICE v2.0 I'm getting an error.

![2021-06-30 03_53_58-Window](https://user-images.githubusercontent.com/43817262/123859506-50729200-d957-11eb-8f78-611f2abc39b9.png)

the error comes when SetAddr is writing `b'A\x00\x00'` & `b'A\x00\x05'`, MCU replies `b'\?'`
But some addresses like `b'A\x00\x04'` write fine, with reply value from MCU, `b'\r'` 

@cbalint13 do you have any clue what's causing this?

Any help would be much appreciated thanks!

**Comment by cbalint13** [comment]
@sengiv 

Let me check, it is also time to rewrite to python3.

**Comment by cbalint13** [comment]
@sengiv 


Can please confirm that it works with python3 now ?

Updated and tested the read/erase/write on stick using python3, please checkout latest git source.

**Comment by sengiv** [comment]
@cbalint13 thanks for quick reply, testing now!

**Comment by sengiv** [comment]
@cbalint13 

Perfect! works well now. Thanks!!
I was about to trash my JTAG ICE programmer then I saw your repo. Saved the day : )

So far the only custom firmware for this programmer I've found is "jtag2updi".
Have you come across other firmwares?

Do you think it's possible to make this into a AVR SPI programmer?

**Comment by cbalint13** [comment]
@sengiv 
 
> Perfect! works well now. Thanks!!

For nothing, also thank you for the investigation time !

> I was about to trash my JTAG ICE programmer then I saw your repo. Saved the day : )
> 
> So far the only custom firmware for this programmer I've found is "jtag2updi".
> Have you come across other firmwares?

No, but truth is i that i stopped searching.

 * I found jtag2updi excelent for all my new michrochip UPDI needs, it works perfect.
 * Also, jtag2updi is avrdude based and I found the firmware + avrdude a pretty solid combo.
 

> Do you think it's possible to make this into a AVR SPI programmer?

Yes it is possible, it was my initial goal but never finished due to lack of time.
For doing it I had to implement a soft-timer based UPDI [1] first that landed into jtag2updi (it was easier).
One have to take the asm-part of bit-banging plus the UPDI logic and land it to AVR SPI programmer firmware.

[1] https://github.com/ElTangas/jtag2updi/commit/443d8115b714ee86a8ecee3fe34edf3b9851f819


Not sure i have the time for it, so ended in middle of process satisfied with the jtag2updi results.

**Comment by sengiv** [comment]
Well I have some time & motivation for the AVR SPI programmer.  : D
But this is new territory for me, so some feedback from you would be great.

Please correct me if I'm wrong.
Since this programmer is basically a USB to TTL converter attached to a ATMEGA16
wouldn't ArduinoISP bootloader with a few changes to pin number work?

**Comment by cbalint13** [comment]
> Well I have some time & motivation for the AVR SPI programmer. : D
> But this is new territory for me, so some feedback from you would be great.
> 
> Please correct me if I'm wrong.
> Since this programmer is basically a USB to TTL converter attached to a ATMEGA16

* Yes is a converter but also implements and speaks that UPDi protocol.

> wouldn't ArduinoISP bootloader with a few changes to pin number work?

* Yes you can change the pin orders, that is easy in order to get it work on any other HW platforms (having AVR).

----

But integrating into avrdude's super popular USB ISP (USBasp) firmware  [1] as a new UPDI target & support is more tricky (that was what I wanted / referred to earlier).

[1] https://www.fischl.de/usbasp
